### ISSUE TITLE
Server Crashing under Load

### ISSUE THREAD

**Issue by rushsteve1** [rcos/observatory-new#62]
**Describe the bug**
Under a moderate load the server crashes with the following bug. I believe it is due to the Database being overwhelmed

**To Reproduce**
1. Start the server
2. Have multiple users try to use it at once
3. Pages begin being unresponsive
4. Error below is in logs

**Additional context**
```
Warning: Responding with 401 Unauthorized catcher.
thread '<unnamed>' panicked at 'Failed to get events: DatabaseError(__Unknown, "database is locked")', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'Expected a successful outcome!', /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.2/src/outcome.rs:162:18
thread '<unnamed>' panicked at 'Expected a successful outcome!', /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.2/src/outcome.rs:162:18
thread '<unnamed>' panicked at 'Expected a successful outcome!', /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.2/src/outcome.rs:162:18
Error: Failed to write response: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }.

```

**Comment by rushsteve1** [comment]
I believe this to be mostly fixed by the configuration change, but if necessary we may need to re-visit this after further testing.
